require("michelkazi.colors")
require("michelkazi.lsp")
require("michelkazi.cmp")
require("michelkazi.lua-line")
require("michelkazi.tmuxnav")
require("michelkazi.treesitter")
require("michelkazi.comment")
-- require("michelkazi.gitsigns")
require("michelkazi.neotree")
require("michelkazi.mappings")
require("michelkazi.todo")
require("michelkazi.db")
require("michelkazi.session")
