#!/bin/bash

# Define color variables in ARGB format
RED="0xffff4500"
GREEN="0xff32cd32"
BLUE="0xff1e90ff"
YELLOW="0xffffd700"
ORANGE="0xffffa500"
PINK="0xffff69b4"
DEFAULT="0xffff4500"

# Check if $BORDERS_ACTIVE_COLOR is set and map it to the corresponding color
case "$BORDERS_ACTIVE_COLOR" in
"red")
  ACTIVE_COLOR=$RED
  ;;
"green")
  ACTIVE_COLOR=$GREEN
  ;;
"blue")
  ACTIVE_COLOR=$BLUE
  ;;
"yellow")
  ACTIVE_COLOR=$YELLOW
  ;;
"orange")
  ACTIVE_COLOR=$ORANGE
  ;;
"pink")
  ACTIVE_COLOR=$PINK
  ;;
*)
  # Default to red if the environment variable is not set or does not match any case
  ACTIVE_COLOR=$DEFAULT
  ;;
esac

# Inactive color (gray) in ARGB format
INACTIVE_COLOR="0xff808080"

# Execute the borders command with the determined active and inactive colors
borders active_color=$ACTIVE_COLOR inactive_color=$INACTIVE_COLOR width=12
