
after-login-command = []

after-startup-command = [
    'exec-and-forget borders',
    'workspace Code',
]

start-at-login = true

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift
# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide.html#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 50
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

gaps.inner.horizontal = [{ monitor."Studio Display" = 20 }, 15]
gaps.inner.vertical = [{ monitor."Studio Display" = 20 }, 15]
gaps.outer.left = [{ monitor."Studio Display" = 20 }, 15]
gaps.outer.bottom = [{ monitor."Studio Display" = 22 }, 15]
gaps.outer.top = [{ monitor."Studio Display" = 22 }, 15]
gaps.outer.right = [{ monitor."Studio Display" = 20 }, 15]

[key-mapping.key-notation-to-key-code]
Messages = 'm'
Code = 'c'
Notes = 'n'
Web = 'w'
Meetings = 'v'
Entertainment = 'e'
Private = 'p'

[mode.main.binding]

# Disable hide
cmd-h = 'macos-native-minimize'
# Also stupid slack huddle command
cmd-shift-h = 'macos-native-minimize'

alt-backtick = 'exec-and-forget open /Applications/Wezterm.app'
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-f = [
    'layout floating tiling',
    'mode main',
] # Toggle between floating and tiling layout
alt-space = ['fullscreen']
alt-h = 'focus left --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'
alt-j = 'focus down --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'
alt-k = 'focus up --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'
alt-l = 'focus right --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-0 = 'workspace 0'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-m = 'workspace Messages'
alt-v = 'workspace Meetings'
alt-c = 'workspace Code'
alt-n = 'workspace Notes'
alt-w = 'workspace Web'
alt-e = 'workspace Entertainment'
alt-p = 'workspace Private'

alt-shift-0 = ['move-node-to-workspace 0', 'workspace 0']
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-m = ['move-node-to-workspace Messages', 'workspace Messages']
alt-shift-c = ['move-node-to-workspace Code', 'workspace Code']
alt-shift-n = ['move-node-to-workspace Notes', 'workspace Notes']
alt-shift-w = ['move-node-to-workspace Web', 'workspace Web']
alt-shift-e = ['move-node-to-workspace Entertainment', 'workspace Entertainment']
alt-shift-v = ['move-node-to-workspace Meetings', 'workspace Meetings']
alt-shift-p = ['move-node-to-workspace Private', 'workspace Private']

alt-ctrl-tab = 'focus-monitor --wrap-around next'
alt-tab = 'workspace-back-and-forth'

alt-shift-tab = 'move-node-to-monitor --wrap-around next'

alt-ctrl-h = ['move-node-to-monitor --wrap-around left', 'focus left --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors']
alt-ctrl-j = ['move-node-to-monitor --wrap-around down', 'focus down --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors']
alt-ctrl-k = ['move-node-to-monitor --wrap-around up', 'focus up --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors']
alt-ctrl-l = ['move-node-to-monitor --wrap-around right', 'focus right --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors']

alt-ctrl-shift-r = 'reload-config'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
r = ['flatten-workspace-tree', 'mode main']                # reset layout
backspace = ['close-all-windows-but-current', 'mode main']
esc = ['reload-config', 'mode main']

[workspace-to-monitor-force-assignment]
# Even numbers on built-in retina display
# Odd Numbers on plugged in wide monitor

1 = 'dell'
2 = 'built-in'
3 = 'dell'
4 = 'built-in'
Code = 'dell'
Messages = 'built-in'
Meetings = 'built-in'
Notes = 'built-in'
Web = 'built-in'
Entertainment = 'built-in'
Private = 'built-in'

# default everything to be in workspace 1
[[on-window-detected]]
check-further-callbacks = true
run = 'move-node-to-workspace 1'
if.during-aerospace-startup = true

# Floating
[[on-window-detected]]
if.app-name-regex-substring = 'Pritunl'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'ChatGPT'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Simulator'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Docker'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = '1Password'
run = 'layout floating'

[[on-window-detected]]
if.window-title-regex-substring = 'Settings'
run = 'layout floating'

[[on-window-detected]]
if.window-title-regex-substring = 'Install'
run = 'layout floating'

[[on-window-detected]]
if.window-title-regex-substring = 'Music'
run = 'move-node-to-workspace Entertainment'

[[on-window-detected]]
if.window-title-regex-substring = 'Spotify'
run = 'move-node-to-workspace Entertainment'

#
# W - Web - workspace

[[on-window-detected]]
if.app-name-regex-substring = 'Chrome'
run = 'move-node-to-workspace Web'

[[on-window-detected]]
if.app-name-regex-substring = 'Safari'
run = 'move-node-to-workspace Web'

[[on-window-detected]]
if.app-name-regex-substring = 'Firefox'
run = 'move-node-to-workspace Web'

# E - Editor workspace
[[on-window-detected]]
if.app-name-regex-substring = 'IntelliJ'
run = 'move-node-to-workspace Code'

[[on-window-detected]]
if.app-name-regex-substring = 'Zed'
run = 'move-node-to-workspace Code'

[[on-window-detected]]
if.app-name-regex-substring = 'Code'
run = 'move-node-to-workspace Code'

[[on-window-detected]]
if.app-name-regex-substring = 'Xcode'
run = 'move-node-to-workspace Code'

# N - Notes/References
[[on-window-detected]]
if.app-name-regex-substring = 'ChatGPT'
run = 'move-node-to-workspace Notes'

[[on-window-detected]]
if.app-name-regex-substring = 'Obsidian'
run = 'move-node-to-workspace Notes'

# T - Terminal workspace
[[on-window-detected]]
if.app-name-regex-substring = 'WezTerm'
run = 'move-node-to-workspace Code'

[[on-window-detected]]
if.app-name-regex-substring = 'Whatsapp'
run = 'move-node-to-workspace Messages'

[[on-window-detected]]
if.app-name-regex-substring = 'Google Meet'
run = 'move-node-to-workspace Meetings'

[[on-window-detected]]
if.app-name-regex-substring = 'Google Calendar'
run = 'move-node-to-workspace Meetings'

[[on-window-detected]]
if.app-name-regex-substring = 'Slack'
run = 'move-node-to-workspace Messages'

[[on-window-detected]]
if.app-name-regex-substring = 'Messages'
run = 'move-node-to-workspace Private'

[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/Users/mkazi/bin:/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

