return {
  "williamboman/mason.nvim",
  dependencies = {
    "williamboman/mason-lspconfig.nvim",
  },
  keys = {
    { "<leader>cm", false },
  },
  opts = {
    ensure_installed = {
      "bash-language-server",
      "diagnostic-languageserver",
      "dockerfile-language-server",
      "hadolint",
      "helm-ls",
      "json-lsp",
      "jsonnet-language-server",
      "lua-language-server",
      "js-debug-adapter",
      "shfmt",
      "rubyfmt",
      "prettierd",
      -- "ruby-lsp",
      "solargraph",
      "rubocop",
      "shellcheck",
      "shfmt",
      "sqlls",
      "stylua",
      "terraform-ls",
      "thriftls",
      "tflint",
      "typescript-language-server",
      "yaml-language-server",
    },
  },
}
